project:
  type: book
  output-dir: "./output"

book:
  title: "The Effect of Climate Change on Economic Decision Making"  # Edit this
  author:
    name: Nikita Tkachenko  # Edit this
    email: natkachenko@dons.usfca.edu  # Edit this
  date: "5/13/2023"  # Edit this
  date-format: "d MMMM, YYYY"
  downloads: [pdf]
   # Edit the abstract
  abstract: |
    As climate change becomes an increasingly inescapable reality, the impact of rising temperatures on 
    society has become a top research priority. A growing body of literature aims to 
    understand the consequences of global warming, such as freshwater depletion, soil degradation, 
    and sea level rise. However, the direct effects of temperature on 
    human behavior are often overlooked, although temperature plays a significant role in how humans 
    interact with their environment and one another. This paper aims to provide a concise overview of 
    the direct effects of temperature on human behavior.
  chapters:
    - index.qmd
    - Chapters/Chapter2.qmd
    # You can add your other chapters here
    - references.qmd
  appendices:
    - Appendices/AppendixA.qmd
    # You can add your appendices here

#  site-url: your_url_here # You can link your website here
#  repo-url: https://github.com/nikitoshina/USFCA-Thesis-Template # you can link github repo here
#  repo-actions: [edit, source, issue] # actions with your github repo
  search: true

thesis:
  # supervisor: 
  #   name: Alessandra Cassar
  #   url: https://quarto.org/
  degree-name: Masters of Science Degree # Edit this
  university: University of San Francisco # Edit this
  department: Department of Economics # Edit this
  program: International Development Economics # Edit this
  acknowledgements: "Thank you to Alessandra, Bruce, and Jesse" # Edit this
  # Do not edit these
  frontpage: "Frontmatter/frontpage.tex"
  toc: "Frontmatter/toc.tex"


bibliography: [references.bib]

execute:
  echo: false
  code-overflow: wrap

format:  
  html:
    theme: cosmo
  quarto-thesis-pdf: 
    urlcolor: black
    

